apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    job_id: "build-123"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        job_id: "build-123"
    spec:
      containers:
      - name: my-app
        image: ndvinhcn/my-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
